{% set name = "napari-emd" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-EMD-{{ version }}.tar.gz
  sha256: 62a82410366777aa19f625f8765071b6ef2dde833825f5b18949f5b0a721913c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - h5py
    - magicgui
    - numpy
    - python >=3.8
    - qtpy          # Imported but not listed as requirement
    - ujson

test:
  imports:
    - napari_emd
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-EMD
  summary: A simple plugin to view .emd files in napari (Velox files)
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/NickiShaw/napari-EMD

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
